fix: use native ES2022 error cause (#5010)
This improves error messages and stack traces. For example:

Before:

Error

at new SubprocessError (.../dist/index.js:41:23)
at ChildProcess.<anonymous> (.../dist/index.js:125:27)
at ChildProcess.emit (node:events:513:28)
at maybeClose (node:internal/child_process:1100:16)
at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

After:

SubprocessError: Signal exit from subprocess.
    at ChildProcess.<anonymous> (.../dist/index.js:122:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 'ERR_SUBPROCESS_SIGNAL_EXIT',
  signal: 'SIGTERM'
}